env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:import/typescript
  - project:./tsconfig.json
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
