env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:import/typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
